### ISSUE TITLE
Tracking testing results for richdocuments 2.2.0

### ISSUE THREAD

**Issue by davitol** [owncloud/richdocuments#278]
### Test Plan for Rich Documents
**Test Setup:**
1. Start Collabora Server with default settings
2. Install and enable RichDocuments 2.2.0

| Test Case | Steps | Expected Result | Results | Comments |
| :-------- | :-----| :-------------- | :-----: | :------- |
**CLI commands** |  |   |
|enable the app via occ command ```occ app:enable richdocuments```| App is enabled| ✅ ||
|disable the app via occ command ```occ app:disable richdocuments```| App is disabled| ✅ ||
**Collabora options** |  |   |
|Configure a Collabora Online server | Server is configured and works| ✅ ||
|Enable edit for specific groups | Check Collabora server is only available for that specific groups| ✅ ||
|Enable access for external apps | Check Collabora is available for that external apps| ✅ ||
|Set a new watermark for Secure View | Check with Collabora personalized Watermark appears| ✅ ||
**Secure View and Downloads** |  |   |
|Having secure view enabled. Try to download a file from Files View| File cannot be downladed. Forbidden file message appears and an exception in spotted in owncloud.log | ✅ ||
|Having secure view enabled. Try to download a file from Favorites| File cannot be downladed. Forbidden file message appears and an exception in spotted in owncloud.log | ✅ ||
|Having secure view enabled. Try to download a file from Share with you | File cannot be downladed. Forbidden file message appears and an exception in spotted in owncloud.log | ✅ ||
|Having secure view enabled. Try to download a file from Shared with others | File cannot be downladed. Forbidden file message appears and an exception in spotted in owncloud.log | ✅ ||
|Having secure view enabled. Try to download a file from Tags| File cannot be downladed. Forbidden file appears and an exception in spotted in owncloud.log | ✅ ||
|Having secure view enabled. Try to download a file from Versions| File cannot be downladed. Forbidden file message appears and an exception in spotted in owncloud.log | ✅ ||
|Having secure view enabled. Try to download a file from an External Storage| File cannot be downladed. Forbidden file message appears and an exception in spotted in owncloud.log | ✅ ||
|Having secure view enabled. Try to download a file selecting more files in files view | File cannot be downladed. Forbidden file message appears and an exception in spotted in owncloud.log | ✅ ||
**Secure View and Collabora** |  |   |
|For shared ODF/DOC/PDF| These files will be opened with watermark in a safe editor | ✅ ||
|Hidden files, for shared ODF/DOC/PDF| These files will be opened with watermark in a safe editor | ✅ ||
**Secure View and Shared Folders**|  |   |
| Share a folder with Secure view enabled|  all other formats than ODF/DOC/PDF will show exception, ODF/DOC/PDF will be opened with watermark in a safe editor | ✅ ||
**Secure View and Restore Versions**|  |   |
| Having secure view enabled. Try to restore an old version |  It is not possible to restore a version in Secure View | ✅ ||

**Comment by davitol** [comment]
## Issues found in QA milestone: [WIP]

- [ ] Tarball from release 2.2.0 RC seems to be not well builthttps://github.com/owncloud/richdocuments/issues/282
- [ ] Secure view options is offered for every kind of file. https://github.com/owncloud/richdocuments/issues/283
- [ ] Secure View options are not available when creating a Guest user https://github.com/owncloud/richdocuments/issues/285

**Comment by davitol** [comment]
## Changelog of bugfixes in richdocuments 2.2.0 RC2:
- [ ] Typo in Encryption warning message https://github.com/owncloud/richdocuments/issues/289
- [ ] Weird behavior when checking Secure View options https://github.com/owncloud/richdocuments/issues/288
- [ ] Secure View options are not available when creating a Guest user https://github.com/owncloud/richdocuments/issues/285
