### ISSUE TITLE
[QA] 2.6.0 Testplan

### ISSUE THREAD

**Issue by jnweiger** [owncloud/richdocuments#416]
## 'Richdocuments' Test Plan

Template: https://github.com/owncloud/QA/tree/master/Server/Test_Plan_richdocuments.md

## Setup
<details><summary>Setup details (click to view)</summary>

* [ ] setup via `make_oc10_apps.sh richdocuments` 2.6.0RC2
    -> https://oc1080-richdocuments-20210730.jw-qa.owncloud.works/owncloud
    -> http://oc1080-richdocuments-20210730.jw-qa.owncloud.works:8025/
</details>

## Testing functionality

Test Case | Expected Result | Result | Related Comment
------------- | -------------- | ----- | ------
occ a:e richdocuments | app gets enabled  | :heavy_check_mark:   |
occ a:dis richdocuments | app gets disabled |  :heavy_check_mark:   |
Configure wopi | connects via WOPI | :heavy_check_mark:   |
Smoke test text document | Basic editing works | :heavy_check_mark:   |
Smoke test spreadsheet | Basic editing works | :heavy_check_mark:   |
Smoke test impress | Basic editing works | :heavy_check_mark:   |
Smoke test impress | Full screen Presentation | :no_entry_sign:  | 
enable pdfviewer | edit chooser popup allows choice | :heavy_check_mark:    | 
Smoke test PDF | option collabora allows to add comments, then download | :heavy_check_mark:    |   
Smoke test PDF | option files_pdfviewer works | :heavy_check_mark:  |
enable texteditor | edit chooser popup allows choice | :heavy_check_mark: | 
Smoke test TXT | option collabora allows text editing | :heavy_check_mark:    |   
Smoke test TXT | option files_textviewer works | :heavy_check_mark: |
Secure view | checkbox grayed out without ee license | :heavy_check_mark: :  |
Secure view | sharing defaults to secure view | :heavy_check_mark: :  |
Secure view | documents have watermark, cannot be downloaded | :heavy_check_mark: :  |
Secure view | still works with invalid or expired license key, until disabled | :heavy_check_mark: :  |

----
----

**Comment by GeraldLeikam** [comment]
## Issues seen while testing

* [ ]

**Comment by jnweiger** [comment]
## changelog testing
* [x] Watermark appears when new setting is set. Even without sharing #400
* [ ] Enable comments on pdfs  #404
* [ ] Use app icon for Open in Collabora action #406
* [ ] Don't log warning message on PUT in favour of debug #407
* [ ] Prevent documents with tabs in filenames / or any other invalid chars from being created
* [x] Only verify path if filename is given, additional log error #418

**Comment by jnweiger** [comment]
Release done :-)
